version: "2"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./htdoc:/usr/share/nginx/html:ro
    ports:
      - 12080:80
  prebiuld:
    image: eugenmayer/gdpr-csp-nginx
    build:
      context: ./
    ports:
      - 10080:80